siteName: Vero Bosschaert
productionUrl: https://verobosschaert.pages.dev
htmlHead: <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/m4rrc0/ctx-css@c/una-scelta/dist/index.css">
languages:
  - code: en
    name: English
    customUrlPrefix: null
    status: published
    isCmsDefault: true
    isWebsiteDefault: true
  - code: FR
    name: français
    customUrlPrefix: null
    status: draft
    isCmsDefault: false
    isWebsiteDefault: false
collections:
  - articles
